[package]
name = "surreal-compose"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = "2.2.1"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
serde_json = "1.0.140"
serde = "1.0.219"
